version: 0.2
phases:
  install:
      runtime-versions:
        nodejs: 16
      commands:
        - npm install
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region eu-central-1 | docker login --username AWS --password-stdin 614007627891.dkr.ecr.eu-central-1.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t nextjs-application:latest .
      - docker tag nextjs-application:latest 614007627891.dkr.ecr.eu-central-1.amazonaws.com/nextjs-application:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 614007627891.dkr.ecr.eu-central-1.amazonaws.com/nextjs-application:latest
      